//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalAccountsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentData
    {
        public int talentID { get; set; }
        public string talentName { get; set; }
        public string imageURL { get; set; }
    }
}
